import type { LaunchpadSeed } from "./types";

export const launchpadSeed: LaunchpadSeed = {
  features: [
    {
      id: "feature-launchpad",
      title: "启动台总览",
      description: "集中展示 Web/PWA 与扩展迁移状态、自动化运行情况。",
      href: "/launchpad",
      icon: "launchpad",
      status: "available",
      tags: ["路线图", "状态"],
      defaultPinned: true,
    },
    {
      id: "feature-workspace",
      title: "会话工作区",
      description: "浏览器端管理多助手对话、主题与实时同步。",
      href: "/workspace",
      icon: "workspace",
      status: "available",
      tags: ["PWA", "Zustand"],
      defaultPinned: true,
    },
    {
      id: "feature-knowledge",
      title: "知识库中心",
      description: "检索团队资料、管理固定资源，支持离线缓存。",
      href: "/knowledge",
      icon: "knowledge",
      status: "available",
      tags: ["文档", "搜索"],
      defaultPinned: true,
    },
    {
      id: "feature-extension",
      title: "浏览器扩展",
      description: "捕获网页选区，通过桥接推送到 Workspace 对话。",
      href: "https://github.com/cinagroup/cinaseek/tree/main/apps/extension",
      icon: "extension",
      status: "in-progress",
      tags: ["Extension", "Bridge"],
      external: true,
    },
    {
      id: "feature-files",
      title: "文件工作台",
      description: "迁移文件列表、批量操作与云端备份能力。",
      href: "/files",
      icon: "files",
      status: "available",
      tags: ["文件", "备份"],
      defaultPinned: true,
    },
    {
      id: "feature-minapps",
      title: "迷你应用中心",
      description: "集中管理 Web 快捷入口与扩展桥接工具。",
      href: "/minapps",
      icon: "minapps",
      status: "available",
      tags: ["快捷入口", "自定义"],
      defaultPinned: true,
    },
    {
      id: "feature-agents",
      title: "智能助手库",
      description: "重构代理管理界面，支持提示词与能力配置。",
      href: "/agents",
      icon: "agents",
      status: "available",
      tags: ["Agent", "配置"],
      defaultPinned: true,
    },
    {
      id: "feature-code",
      title: "工程工具集",
      description: "整合 CLI、模型与终端配置，复刻桌面端代码工具链。",
      href: "/code",
      icon: "code",
      status: "available",
      tags: ["工程", "自动化"],
    },
    {
      id: "feature-notes",
      title: "团队笔记",
      description: "迁移 Markdown 笔记、AI 草稿与多维检索能力。",
      href: "/notes",
      icon: "notes",
      status: "available",
      tags: ["知识", "协作"],
    },
    {
      id: "feature-translate",
      title: "翻译与润色",
      description: "将 Electron 翻译工作台迁移至 Web，结合扩展授权。",
      href: "/translate",
      icon: "translate",
      status: "available",
      tags: ["多语言", "工具"],
    },
    {
      id: "feature-memory",
      title: "记忆中心",
      description: "全新记忆工作台，支持用户分组与模型配置。",
      href: "/memory",
      icon: "memory",
      status: "available",
      tags: ["上下文", "知识"],
      defaultPinned: true,
    },
    {
      id: "feature-settings",
      title: "设置中心",
      description: "浏览器端统一管理主题、快捷键、网页搜索供应商与系统能力。",
      href: "/settings",
      icon: "settings",
      status: "available",
      tags: ["PWA", "个性化", "搜索"],
      defaultPinned: true,
    },
  ],
  automations: [
    {
      id: "automation-selection-forwarding",
      title: "浏览器选区实时转发",
      description: "Manifest v3 背景脚本通过消息桥将网页选区推送到 Workspace。",
      status: "active",
      cadence: "实时",
      owner: "Extension Bridge",
      tags: ["Extension", "Bridge"],
      external: true,
      href: "https://github.com/cinagroup/cinaseek/tree/main/apps/extension",
    },
    {
      id: "automation-knowledge-sync",
      title: "知识库增量同步",
      description: "定时将 Markdown、FAQ 与外部数据源同步到 PWA IndexedDB。",
      status: "scheduled",
      cadence: "每日 07:00",
      owner: "Next.js Route Handler",
      tags: ["知识库", "同步"],
      href: "/knowledge",
    },
    {
      id: "automation-backup",
      title: "文件备份迁移",
      description: "替换 Electron WebDAV 流程为云端 API 与后台任务队列。",
      status: "planned",
      cadence: "规划中",
      owner: "BFF 服务",
      tags: ["备份", "存储"],
    },
  ],
  updates: [
    {
      id: "update-20241018",
      title: "Workspace PWA 预览",
      summary: "上线 App Router 布局、会话状态迁移与 Socket.io 状态指示。",
      date: "2024-10-18T09:00:00.000Z",
      status: "shipped",
      tags: ["Workspace", "PWA"],
      href: "/workspace",
    },
    {
      id: "update-20241019",
      title: "知识库中心上线",
      summary: "完成知识库领域模型抽离、搜索与固定功能迁移。",
      date: "2024-10-19T10:00:00.000Z",
      status: "shipped",
      tags: ["知识库"],
      href: "/knowledge",
    },
    {
      id: "update-20241021",
      title: "扩展桥接联调",
      summary: "Manifest v3 与 PWA 长连接打通，支持选区推送。",
      date: "2024-10-21T04:00:00.000Z",
      status: "in-progress",
      tags: ["Extension", "Bridge"],
      href: "https://github.com/cinagroup/cinaseek/tree/main/apps/extension",
      external: true,
    },
    {
      id: "update-20241025",
      title: "文件工作台重构",
      summary: "上线 Web 文件工作台，支持置顶筛选、排序与示例创建。",
      date: "2024-10-25T02:00:00.000Z",
      status: "shipped",
      tags: ["文件", "备份"],
      href: "/files",
    },
    {
      id: "update-20241027",
      title: "笔记与翻译工作台上线",
      summary: "Web 端新增团队笔记与翻译工作流，补齐核心工具集。",
      date: "2024-10-27T08:00:00.000Z",
      status: "shipped",
      tags: ["Notes", "Translate"],
      href: "/notes",
    },
    {
      id: "update-20241029",
      title: "设置中心上线",
      summary: "推出 PWA 设置页，支持主题、快捷键与扩展能力迁移。",
      date: "2024-10-29T06:00:00.000Z",
      status: "shipped",
      tags: ["Settings"],
      href: "/settings",
    },
    {
      id: "update-20241030",
      title: "迷你应用中心上线",
      summary: "迁移 Electron 迷你应用功能，支持搜索、自定义与置顶策略。",
      date: "2024-10-30T05:00:00.000Z",
      status: "shipped",
      tags: ["Mini Apps"],
      href: "/minapps",
    },
    {
      id: "update-20241031",
      title: "记忆中心迁移",
      summary: "完成用户记忆管理、模型配置与浏览器端持久化。",
      date: "2024-10-31T05:00:00.000Z",
      status: "shipped",
      tags: ["Memory", "上下文"],
      href: "/memory",
    },
  ],
};
