import type { MiniAppsSeed } from "./types";

export const miniAppsSeed: MiniAppsSeed = {
  categories: [
    {
      id: "workspace",
      name: "工作区",
      description: "连接会话、历史与翻译等核心工作流。",
      accent: "#60a5fa",
    },
    {
      id: "knowledge",
      name: "知识检索",
      description: "快速打开知识库、文件与资料中心。",
      accent: "#a855f7",
    },
    {
      id: "productivity",
      name: "效率工具",
      description: "集合各类迁移辅助与团队协作工具。",
      accent: "#facc15",
    },
    {
      id: "extension",
      name: "扩展桥接",
      description: "管理 Manifest v3 扩展与桥接状态。",
      accent: "#34d399",
    },
    {
      id: "creative",
      name: "创作实验室",
      description: "接入绘图、稿件与灵感采集入口。",
      accent: "#fb7185",
    },
  ],
  tags: [
    { id: "pwa", label: "PWA" },
    { id: "workspace", label: "工作区" },
    { id: "docs", label: "文档" },
    { id: "extension", label: "扩展" },
    { id: "productivity", label: "效率" },
    { id: "creative", label: "创作" },
  ],
  apps: [
    {
      id: "miniapp-workspace",
      name: "会话工作区",
      description: "跳转至 Web 会话空间，管理助手与主题。",
      url: "/workspace",
      category: "workspace",
      icon: "💬",
      tags: ["pwa", "workspace"],
      pinned: true,
      addedAt: "2024-10-20T10:00:00.000Z",
      lastLaunchedAt: "2024-10-27T09:45:00.000Z",
      launchCount: 42,
    },
    {
      id: "miniapp-history",
      name: "对话历史检索",
      description: "按主题回顾历史消息，支持关键词搜索。",
      url: "/history",
      category: "knowledge",
      icon: "🗂️",
      tags: ["docs"],
      pinned: true,
      addedAt: "2024-10-20T10:05:00.000Z",
      lastLaunchedAt: "2024-10-26T16:20:00.000Z",
      launchCount: 18,
    },
    {
      id: "miniapp-knowledge",
      name: "知识库中心",
      description: "浏览迁移档案、常见问题与固定资源。",
      url: "/knowledge",
      category: "knowledge",
      icon: "📚",
      tags: ["docs", "workspace"],
      addedAt: "2024-10-21T07:30:00.000Z",
      lastLaunchedAt: "2024-10-25T05:12:00.000Z",
      launchCount: 25,
    },
    {
      id: "miniapp-translate",
      name: "翻译工作台",
      description: "调用多模型翻译与润色，适配浏览器权限。",
      url: "/translate",
      category: "productivity",
      icon: "🌐",
      tags: ["productivity"],
      addedAt: "2024-10-22T03:15:00.000Z",
      lastLaunchedAt: "2024-10-27T02:05:00.000Z",
      launchCount: 12,
    },
    {
      id: "miniapp-extension-docs",
      name: "扩展桥接指南",
      description: "查看浏览器扩展的安装、权限与桥接状态。",
      url: "https://github.com/cinagroup/cinaseek/tree/main/apps/extension",
      category: "extension",
      icon: "🧩",
      tags: ["extension"],
      pinned: true,
      addedAt: "2024-10-23T11:00:00.000Z",
      lastLaunchedAt: "2024-10-26T08:30:00.000Z",
      launchCount: 31,
    },
    {
      id: "miniapp-creative-ideas",
      name: "创作灵感板",
      description: "收集扩展与 PWA 生成的灵感、画稿与脚本。",
      url: "https://www.figma.com/file/preview/cinaseek-board",
      category: "creative",
      icon: "✨",
      tags: ["creative"],
      addedAt: "2024-10-24T06:45:00.000Z",
      launchCount: 7,
    },
  ],
};
